---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=dragonflydb/dragonfly-operator
  - https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/v1.1.8/manifests/crd.yaml
  - helm-release.yaml
  - rbac.yaml
configMapGenerator:
  - name: dragonfly-dashboard
    files:
      # renovate: datasource=github-releases depName=dragonflydb/dragonfly-operator
      - dragonfly-dashboard.json=https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/v1.1.8/monitoring/grafana-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana_folder: "dragonfly"
  labels:
    grafana_dashboard: "true"
