---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - helm-release.yaml
  - pod-monitor.yaml
  - replication-source.yaml
  - external-secret.yaml
configMapGenerator:
  - files:
      - lumi.sensor_occupy.agl1.js=./assets/lumi.sensor_occupy.agl1.js
    name: zigbee2mqtt-basement-assets
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: zigbee2mqtt-basement
      app.kubernetes.io/name: zigbee2mqtt-basement
