---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - helm-release.yaml
  - pod-monitor.yaml
  - replication-source.yaml
  - external-secret.yaml
commonLabels:
  app.kubernetes.io/name: zigbee2mqtt-basement
  app.kubernetes.io/instance: zigbee2mqtt-basement
configMapGenerator:
  - name: zigbee2mqtt-basement-assets
    files:
      - lumi.sensor_occupy.agl1.js=./assets/lumi.sensor_occupy.agl1.js
generatorOptions:
  disableNameSuffixHash: true
