---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-volume-snapshot-class
spec:
  dependsOn:
    - name: openebs
    - name: snapshot-controller
      namespace: kube-tools
  interval: 15m
  chart:
    spec:
      chart: k8s-resource
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: mirceanton-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: openebs-volume-snapshot-class
