---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/talos-flux/flux
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  # postBuild:
  #   substituteFrom:
  #     - kind: ConfigMap
  #       name: cluster-settings
  #       optional: false
  #     - kind: Secret
  #       name: cluster-secrets
  #       optional: false
