---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/base/flux/repositories
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
