# IMPORTANT: This file is not tracked by flux and should never be. Its
# purpose is to only install the Flux components and CRDs into your cluster.
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gotk-components.yaml
patches:
  # Remove the network policies that does not work with k3s
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: not-used
    target:
      group: networking.k8s.io
      kind: NetworkPolicy
  # prevent deletion of namespace by flux
  - patch: |
      - op: add
        path: /metadata/labels/kustomize.toolkit.fluxcd.io~1prune
        value: disabled
    target:
      kind: Namespace
      version: v1
      name: flux-system
  # Remove image-automation-controller as we dont use it
  # - patch: |
  #     $patch: delete
  #     apiVersion: apiextensions.k8s.io/v1
  #     kind: CustomResourceDefinition
  #     metadata:
  #       name: imageupdateautomations.image.toolkit.fluxcd.io
  #   target:
  #     group: apiextensions.k8s.io
  #     kind: CustomResourceDefinition
  #     name: imageupdateautomations.image.toolkit.fluxcd.io
  - patch: |
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: image-automation-controller
    target:
      kind: Deployment
      version: v1
      name: image-automation-controller
  # Remove image-reflector-controller as we dont use it
  - patch: |
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: image-reflector-controller
    target:
      kind: Deployment
      version: v1
      name: image-reflector-controller
  # Increase the number of reconciliations that can be performed in parallel and bump the resources limits
  # https://fluxcd.io/flux/cheatsheets/bootstrap/#increase-the-number-of-workers
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kube-api-qps=500
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kube-api-burst=1000
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s
    target:
      kind: Deployment
      name: (kustomize-controller|helm-controller|source-controller)
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 30m
                    memory: 300Mi
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 30m
                    memory: 100Mi
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 15m
                    memory: 350Mi
    target:
      kind: Deployment
      name: source-controller
  # Enable in-memory-kustomize builds
  # https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-in-memory-kustomize-builds
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: temp
          emptyDir:
            medium: Memory
    target:
      kind: Deployment
      name: kustomize-controller
  # Enable Helm near OOM detection
  # https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-helm-near-oom-detection
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=OOMWatch=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --oom-watch-memory-threshold=95
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --oom-watch-interval=500ms
    target:
      kind: Deployment
      name: helm-controller
