---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cert-manager-issuers
  interval: 10m
  path: ./kubernetes/kube-nas/apps/nginx-ingress/nginx/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
