---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-velocity-proxy-data2
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
