# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: velocity-proxy-env
type: Opaque
stringData:
    CFG_RCON_FORWARDING_SECRET: ENC[AES256_GCM,data:o2eFgg==,iv:V9WWVOVuQ/FSL8R8bH4xiYwlOGAq3h3G2NCXHg5Y5P8=,tag:RDyEijwd1mzh+OF1cj9Kog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T20:25:37Z"
    mac: ENC[AES256_GCM,data:CB2laCMUDl/6nCSYRiBGbNplhQX3khy7mPWkDkZ21Cp1jLAGfWQ8hFVXd2Q2U2rQxNCspYPcTbr7Q+9p6MQi7Tldd3j/4SMvjSJAp2KVupt0Jg6RxMgfnT6fj2kr1UIih112+Fnp+GAxb6MYRa8twj+WPNzHb7HQw9sA/+DSf0s=,iv:hy8BEdGbbcnqx2syTIphVgYreKzKlXCclE9WKDbeVOI=,tag:b6GJhQi9zIrcBxXDhPP4Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
