---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-atlantis
  namespace: flux-system
  annotations:
    backstage.io/discovery: enabled
    backstage.io/name: atlantis
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/atlantis/atlantis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-cert-manager
    - name: apps-rook-ceph-cluster
    - name: apps-traefik-forward-auth
    - name: apps-external-secrets
