---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-atlantis
  namespace: flux-system
  annotations:
    backstage.io/discovery: enabled
    backstage.io/name: atlantis
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/atlantis/atlantis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-cert-manager
    - name: apps-rook-ceph-cluster
    - name: apps-traefik-forward-auth
    - name: apps-external-secrets

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname apps-atlantis-tyriis
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: atlantis
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/talos-flux/apps/atlantis/atlantis/tyriis
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: apps-cert-manager
    - name: apps-rook-ceph-cluster
    - name: apps-traefik-forward-auth
