---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0-6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 30d
    # https://cloudnative-pg.io/documentation/current/wal_archiving/
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg-backups/
      endpointURL: https://minio.techtales.io
      serverName: &clustername postgres17
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY

  # https://cloudnative-pg.io/documentation/current/recovery/#recovery-from-an-object-store
  # bootstrap:
  #   recovery:
  #     source: *clustername
  # externalClusters:
  #   - name: *clustername
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *clustername

  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: postgres16

  externalClusters:
    - name: postgres16
      connectionParameters:
        host: postgres16-rw
        user: postgres
        dbname: postgres
        sslmode: require
      password:
        name: postgres-superuser
        key: password
