---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jazzlyn-gh-actions-demo
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
      interval: 30m
  values:
    runnerScaleSetName: arc-runner-set-gh-actions-demo
    githubConfigUrl: https://github.com/jazzlyn/gh-actions-demo
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
        imagePullSecrets:
          - name: jazzlyn-registry-dockerhub
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.321.0@sha256:d968199e3772ef831c34eb8edd495ef9eb99339a2f7176d4f1774f252f7903fb
            command: ["/home/runner/run.sh"]
            volumeMounts:
              - name: jazzlyn-registry-dockerhub
                mountPath: /home/runner/config.json
                subPath: config.json
              - name: docker-config
                mountPath: /home/runner/.docker
        initContainers:
          - name: dockerconfigwriter
            image: busybox@sha256:768e5c6f5cb6db0794eec98dc7a967f40631746c32232b78a3105fb946f3ab83
            command:
              - /bin/sh
              - -ec
              - cp /home/runner/config.json /home/runner/.docker/config.json
            volumeMounts:
              - name: jazzlyn-registry-dockerhub
                mountPath: /home/runner/config.json
                subPath: config.json
              - name: docker-config
                mountPath: /home/runner/.docker
        volumes:
          - name: jazzlyn-registry-dockerhub
            secret:
              secretName: jazzlyn-registry-dockerhub
              items:
                - key: .dockerconfigjson
                  path: config.json
          - name: docker-config
            emptyDir: {}
    controllerServiceAccount:
      namespace: github
      name: gha-runner-scale-set-controller
  valuesFrom:
    - kind: Secret
      name: jazzlyn-runners
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: jazzlyn-runners
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: jazzlyn-runners
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app jazzlyn-gh-actions-demo
spec:
  selector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: *app
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
