---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-lobby-world2
spec:
  dependsOn:
    - name: external-secret-minecraft-proxy-forwarding
    - name: external-secret-minecraft-rcon
    - name: external-secret-minecraft-curseforge-api-key
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java21@sha256:6859bd9ff36447128df08826c3846bcfa66e7d6e27ccf2f6f4f2b9d262bf5ffd
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  exec: &mc-health { command: ["mc-health"] }
                  failureThreshold: 20
              readiness: *probes
              startup:
                <<: *probes
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *mc-health
            envFrom:
              - secretRef:
                  name: minecraft-rcon
              - secretRef:
                  name: curseforge-api-key
            env:
              # https://docker-minecraft-server.readthedocs.io/en/latest/variables
              TZ: ${SETTING_TZ}
              EULA: "true"
              TYPE: "PAPER"
              # TODO renovate
              VERSION: "1.21.4"
              DIFFICULTY: peaceful
              OPS: "tyriis,jazzlyin"
              MAX_PLAYERS: "25"
              ALLOW_NETHER: "false"
              ENABLE_COMMAND_BLOCK: "true"
              GENERATE_STRUCTURES: "false"
              SPAWN_ANIMALS: "false"
              SPAWN_MONSTERS: "false"
              SPAWN_NPCS: "false"
              # SPAWN_PROTECTION: "0"
              VIEW_DISTANCE: "14"
              HARDCORE: "false"
              MODE: creative
              MOTD: "techtales lobby"
              PVP: "false"
              LEVEL_TYPE: FLAT
              ONLINE_MODE: "false"
              MEMORY: "1024M"
              ENABLE_RCON: "true"
              CF_PARALLEL_DOWNLOADS: "4"
              MODS_FILE: /config/plugins.txt
              USE_AIKAR_FLAGS: "true"
              SNOOPER_ENABLED: "true"
              MAX_BUILD_HEIGHT: "256"
              LEVEL: lobby
              SERVER_NAME: lobby
              STOP_SERVER_ANNOUNCE_DELAY: "60"
              STOP_DURATION: "60"
              ENABLE_WHITELIST: "false"
              ENABLE_ROLLING_LOGS: "true"
              LOG_TIMESTAMP: "true"
              # REMOVE_OLD_MODS: "true"
              REPLACE_ENV_DURING_SYNC: "true"
              CFG_PROXY_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: minecraft-proxy-forwarding
                    key: forwarding.secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            ports:
              - name: java
                containerPort: 25565
              - name: rcon
                containerPort: 25575

            resources:
              requests:
                cpu: 100m
                memory: 1Gi

    service:
      minecraft:
        controller: minecraft
        type: ClusterIP
        ports:
          java:
            port: 25565
            protocol: TCP
      rcon:
        controller: minecraft
        type: ClusterIP
        ports:
          rcon:
            port: 25575
            protocol: TCP

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m

    persistence:
      data:
        existingClaim: minecraft-lobby-world-data2
        advancedMounts:
          minecraft:
            app:
              - path: /data
      config:
        type: configMap
        name: minecraft-lobby-world-config2
        globalMounts:
          - path: /config/spigot.yml
            subPath: spigot.yml
            readOnly: true
          - path: /config/paper-global.yml
            subPath: paper-global.yml
            readOnly: true
          - path: /config/plugins.txt
            subPath: plugins.txt
            readOnly: true
