# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    labels:
        kustomize.toolkit.fluxcd.io/prune: disabled
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LWGDmudeJQ/7ZHy75DXYGfik3UY=,iv:27CI1znsOuw3tvhd39AN/CLTboXXp5V0yfpGiVgsPzs=,tag:cmifoigmu1Uq8yeI14dnSg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:V8jIdBxr6/Y+J1VWeaB18sL3DakdmF9enIwMExvPuNTyiSMk,iv:7tsv/BlfmCc5QrqhIJbIbT/xIDbBnf8ITKityQ55wGs=,tag:2AhU/1t9LvyaBgLanlBdbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVlFoYmgyTDZHNFdNQnZM
            UlpKYTFDWGVtWEhRUmZEemp3TFRUTkV2VTFBCjdhWnBhSGR5ZU01aGxRYWhIc0Ew
            QUtYM2s2WWZVREptV1lsRXIrdHIyV1kKLS0tICtVKzZ3TXpyYjFRa0dsbVdsYkpP
            SHlHS1N5UWRLbGRZWkFQa2ZORk91bXcKi0d9metxL4K26w7fLNn25O/4/wJPYwpK
            DDUb3MaTsNARCtgqiqAaJEb3awE3MMWQTwqKcGANpDIivIrUsh5CNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T23:34:34Z"
    mac: ENC[AES256_GCM,data:utsLM1xUmbihBSLYjlT3FTcx0wZkLsT/OtDaPeYnwP6hOJtthEb2srPrP7Yp3pK5TZNGrBloTnqxrixxWMaV6PQE+BvfpjJUxOfwpeglzoyAtr1rFN8KFMii/Jy6uHnZSqzDTd0lEeNeMD+KRQKKIJB4nUeiX/Jl3XSdKZs0rcM=,iv:0WekUnrnO9PAE2bKeZT+XUeiUJoI/xRU4OoCtSMegh8=,tag:Q+Xy9l2ttxa61+U3nc5Ezw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
