---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vault-snapshot-agent-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kube-nas-vault
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: APPROLE_ROLE_ID
      remoteRef:
        key: infra/kube-nas/secops/vault/approle-snapshot-agent
        property: role_id
    - secretKey: APPROLE_SECRET_ID
      remoteRef:
        key: infra/kube-nas/secops/vault/approle-snapshot-agent
        property: secret_id

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vault-snapshots-gcp-sa
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kube-nas-vault
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: infra/kube-nas/secops/vault/vault-snapshots-gcp-sa
        property: credentials

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vault-snapshots-gcs
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kube-nas-vault
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: BUCKET_NAME
      remoteRef:
        key: infra/kube-nas/secops/vault/vault-snapshots-gcs
        property: bucket-name
