---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-playground-world-data
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
