---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # need to be more in production
  storageClassName: openebs-hostpath
