---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-local
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.60
  share: /export/nfs-csi/kube-nas
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - tcp
  - timeo=600
  - retrans=2
