---
apiVersion: dbman.hef.sh/v1alpha3
kind: Database
metadata:
  name: &name bluemap
spec:
  credentials:
    usernameSecretRef:
      name: minecraft-bluemap-postgres
      key: INIT_POSTGRES_USER
    passwordSecretRef:
      name: minecraft-bluemap-postgres
      key: INIT_POSTGRES_PASS
  databaseName: *name
  databaseServerRef:
    namespace: database
    name: postgres17
  prune: false
