---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-database-bluemap
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: external-secret-minecraft-bluemap-postgres
      namespace: gaming
  interval: 15m
  chart:
    spec:
      chart: k8s-resource
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: mirceanton-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-database-bluemap
