---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - helm-release.yaml
configMapGenerator:
  - name: minecraft-database-bluemap
    files:
      - values.yaml=./database.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomize-config.yaml
