---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-public-playground-world-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
