---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-playground-world-data
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: minecraft-playground-world-data
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
