---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - database.yaml # only required for init
  - bunkerweb-database-secret.sops.yaml
  - rbac.yaml
  - helm-release.yaml
