---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bunkerweb-database-secret.sops.yaml
  - database.yaml
  - rbac.yaml
  - helm-release.yaml
