---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname dbman
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  path: ./kubernetes/kube-nas/apps/database-system/dbman/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  targetNamespace: database-system
  timeout: 3m
  retryInterval: 1m
  wait: true
