---
# https://artifacthub.io/packages/helm/external-dns/external-dns?modal=values
fullnameOverride: external-dns-opnsense
logLevel: info
interval: 2m
provider:
  name: webhook
  managedRecordTypes:
    - A
    - AAAA
  webhook:
    image:
      repository: ghcr.io/jobs62/opnsense_unbound_external-dns_webhook
      tag: v0.4.5@sha256:22d3bd25bacaa0a8445a746d6541a8994bcb54e6047f5a079574adc792f88034
    env:
      - name: OPNSENSE_SECRET
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-opnsense-credentials
            key: OPNSENSE_API_SECRET
      - name: OPNSENSE_KEY
        valueFrom:
          secretKeyRef:
            name: *secret
            key: OPNSENSE_API_KEY
      - name: OPNSENSE_BASE
        value: http://opnsense.techtales.io
      - name: OPNSENSE_ALLOW_INVALID_CERTS
        value: "false"
      - name: OPNSENSE_DOMAIN_FILTERS
        value: '[".techtales.io"]'
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
  - --ignore-ingress-tls-spec
  - --annotation-filter=external-dns/opnsense in (true)
  - --webhook-provider-url=http://localhost:8800
policy: sync
sources:
  - ingress
  - service
  - crd
registry: noop
domainFilters:
  - techtales.io
txtPrefix: k8s.talos-flux.
txtOwnerId: talos-flux
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: *secret
