---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - helm-release.yaml
configMapGenerator:
  - name: external-dns-opnsense-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomize-config.yaml
