---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dbman
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: dbman
      version: 0.123.2
      sourceRef:
        kind: HelmRepository
        name: dbman-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: RUST_LOG
        value: info
