---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dbman
spec:
  interval: 30m
  chart:
    spec:
      chart: dbman
      version: 0.123.2
      sourceRef:
        kind: HelmRepository
        name: dbman-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  timeout: 15m
  values:
    env:
      - name: RUST_LOG
        value: info
