---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/kube-nas/apps/kube-system/metrics-server/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
