---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tyriis-terraform-github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tyriis-terraform-github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tyriis-terraform-github-runner
    namespace: github
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: tyriis-terraform-github-runner
spec:
  roles: ["os:admin"]
