# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio-env
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:v7psJAGwot7+hg==,iv:hP6f0P0F5eDuNnixg622ZdB+jeoEuQkWtaIHvMMYtGA=,tag:r7jrBItaB0MT+JVapXcvTA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:zsuCm9SGevz7UA==,iv:9p4F0PGRtL7UGR5LfCrMO2+si5gTyGq9KwawRwk4IX8=,tag:otnMUDLHWEAtD/31CaLtRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzRWUkxIMnA1Nm5MSFVP
            anliQ3F3R1VyWVVNak5mUm5ST3dsSnFRY1hrCkpONU50NGsyUWlhNkYyL3lqN1h5
            VXdSZ0g2NnFsS0loMERMWmZIbGdob28KLS0tIE83RHBlY2FYd0F0YklBRThQd2tl
            TVM4dVYwY3ExYkIxSmJoK3V5VEJNQ2MKs9lDocwW5M7BmdvfvOABbjuffo16CJok
            djKyN7RS86g3cstMR5X4uKoC+UFS6F4+xkNVtJoc6mZS71ZN4RU2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T21:09:48Z"
    mac: ENC[AES256_GCM,data:8tP8lBAril8ZJluPI4a+Eim65ZF6v0+c1XI0e1vsStZ4SdLTEeY933fHmurRO9qD9H9JDopQdxfKfnxbNMkldwz+ycqOgWyWIeh3s/iXbulaG48e9CnPW6mPU+soLo8cTHxpWpEFYnC23Vui0vRt/Mzt+BgbpeRQGIQJDSSIsi8=,iv:O5G5Hnqqa7931GuyO60z1YJ2ncioBx6qNfzIBacn/98=,tag:T8sekJ8jXgQmmuMscSQqLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
