---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.techtales.io
  share: /volume1/talos-nfs-test
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-kube-nas
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.60
  share: /export/data/csi
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - tcp
  - timeo=600
  - retrans=2
