---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname openebs
  namespace: flux-system
spec:
  targetNamespace: openebs-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/kube-nas/apps/openebs-system/openebs/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  retryInterval: 1m
  timeout: 5m

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname openebs-volume-snapshot-class
  namespace: flux-system
spec:
  targetNamespace: openebs-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/kube-nas/apps/openebs-system/openebs/volume-snapshot-class
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  retryInterval: 1m
  timeout: 5m
