---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kms-vault-unseal.sops.yaml
  - secret.sops.yaml
  - persistent-volume-claim.yaml
  - replication-destination.yaml
  - replication-source.yaml
  - helm-release.yaml
