---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-ops
  namespace: flux-system
spec:
  # as we use webhooks, this does not need to be aggressive
  interval: 2h
  url: https://github.com/tyriis/home-ops.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include kubernetes directory only
    !/kubernetes
