---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - replication-destination.yaml
  - persistent-volume-claim.yaml
  - replication-source.yaml
  - helm-release.yaml
commonLabels:
  app.kubernetes.io/name: minecraft-survival-world
  app.kubernetes.io/instance: minecraft-survival-world
configMapGenerator:
  - name: minecraft-survival-world-config
    files:
      - spigot.yml=config/spigot.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
