# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-survival-world-data-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gfHEDIwye9q/8v/eaFAZKah/xa9J3iq60ipPyfVu9VTe4TLITulElRIL1vQJJaiLs5GaRAz8/DXtNpb635xLb6OZgUYa/EwHb21zEsY=,iv:iSW0mFDl85ji0mBggheW//veq1WZXd4fgCVBH2Wdpyc=,tag:LuKxbttxTbRCPSQdTFM7lQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:deqYLQ8LvCqL28PyUMJ1hpJJtP4Fy2UZiJU0yNR1DM7PEUr+L2aOCsKHEg3TfQ24IvS8znp8EXT4NnW+ZSpbSQ==,iv:R6v77Jx9/3IMBVdkzjW9r1JGkz8+Z/L4gRisNlv/+q8=,tag:PUzVkpGv22Y+GoDfaEiMug==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T01:10:10Z"
    mac: ENC[AES256_GCM,data:9W5CfZ1Df7A91HMCKlCQz0nUkifn0iH5S5lvcwQ2U9AaCZiIi2wM8qzTiQzBR6qWdv9mpc2pqjuHUvXrZd64qGJoj1roebTblaXaZ5HA708Lyuc9tzej8oKJNK0PJZlQCV0/BlAiRR8kRN/09RbtMFc/l6oQEME5CKx16ZgbRv0=,iv:tl/N0uVAA7Un8FslI+Xn3vMKLal36nwAWAU7JSNYvKM=,tag:n0SFZz8nvQVK6xXvimEJSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
