# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-survival-world-data-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gfHEDIwye9q/8v/eaFAZKah/xa9J3iq60ipPyfVu9VTe4TLITulElRIL1vQJJaiLs5GaRAz8/DXtNpb635xLb6OZgUYa/EwHb21zEsY=,iv:iSW0mFDl85ji0mBggheW//veq1WZXd4fgCVBH2Wdpyc=,tag:LuKxbttxTbRCPSQdTFM7lQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:deqYLQ8LvCqL28PyUMJ1hpJJtP4Fy2UZiJU0yNR1DM7PEUr+L2aOCsKHEg3TfQ24IvS8znp8EXT4NnW+ZSpbSQ==,iv:R6v77Jx9/3IMBVdkzjW9r1JGkz8+Z/L4gRisNlv/+q8=,tag:PUzVkpGv22Y+GoDfaEiMug==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T11:24:49Z"
    mac: ENC[AES256_GCM,data:p07q3WmKVOeUyAW4k7UPStXvKZh0SDjsC7WI2k36bEQfv9GpQVfmcAGyQQFRdjHchEG0rEyDvKouYj94uIdY9KkUhvsqLPAXWxaLx0rZkbIlb+m61TPr/ks8hRw8UQDfd8VcIBWE2ArGPbkr+s05N6fticFuaUk9nVDCnKuPW98=,iv:ysA672NrA7T2SR0h7Ng5rtS48EZXTGWwxiO/SuC8Tac=,tag:s3hKZcrdsPH0eL4MVmcPkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-survival-world-data-2025-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:83ArddoA2iP4bS7U+eceqY8KLrvbhM2ttRystILXpTuDmHSRZoqx0e3yQtaKTOqzdopQ/xUZC6tJ41+CN20uwggTizB02jF/A3i/pzsAm94uEg==,iv:i7QeJs70i7ZsNaI5u1MKG1jGsQTmP5riTaqO2EzmR84=,tag:m5Y11ECG4H4kv/P+BV5Sdg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:deqYLQ8LvCqL28PyUMJ1hpJJtP4Fy2UZiJU0yNR1DM7PEUr+L2aOCsKHEg3TfQ24IvS8znp8EXT4NnW+ZSpbSQ==,iv:R6v77Jx9/3IMBVdkzjW9r1JGkz8+Z/L4gRisNlv/+q8=,tag:PUzVkpGv22Y+GoDfaEiMug==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T11:24:49Z"
    mac: ENC[AES256_GCM,data:p07q3WmKVOeUyAW4k7UPStXvKZh0SDjsC7WI2k36bEQfv9GpQVfmcAGyQQFRdjHchEG0rEyDvKouYj94uIdY9KkUhvsqLPAXWxaLx0rZkbIlb+m61TPr/ks8hRw8UQDfd8VcIBWE2ArGPbkr+s05N6fticFuaUk9nVDCnKuPW98=,iv:ysA672NrA7T2SR0h7Ng5rtS48EZXTGWwxiO/SuC8Tac=,tag:s3hKZcrdsPH0eL4MVmcPkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
