---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: linkwarden-data
spec:
  sourcePVC: linkwarden-data
  trigger:
    schedule: "43 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: linkwarden-data-volsync
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 2Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      weekly: 4
