# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-data-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:xAKGS9rtsA5p/BmHLQeTBSyqVxxqUlnIx/G/CjgQh5MI8atjW0N8Vk76AUfQPtwzZ1EYGUrSkpQRhP6w/Q/iSl07gH62,iv:CfZIhqU5jo84Y4YDyYDM7DIA8rhdJ82alPZPGzRLjH4=,tag:M5xWJ34Y7WdJCRSEj0IjZQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:2iglLRQ9GEXNrj0hbs4xr33hSc+ZTTwXBXNhrfmrEZTFtZ8QpItbz8+KKXzCi+ZGd58xN1QftiwO19Y1hRAFwA==,iv:RTOIyyroBSVDn1KbxY6wEytm0CD/UpRM83w/InRgFY0=,tag:M+Qgd7+RKyI02ZyRCqnYrQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T18:21:01Z"
    mac: ENC[AES256_GCM,data:d46KTRxAGnhqBeor22mY1k7Z6kEoTJTXS7Bs8YU36Mi8Z/i02gekml18MvI8Jf+E/QvgicLjiMoBESfyLWjAUc3TEZOADmyW3g/suE+G0M7JrsqGWMI6iYwRm8j13Wc+N8XaE7hK4AJffTsBWiS7ooTsZaRDa+cvk3Bl9B4DcOk=,iv:8XWhWULfikBxIIzhC4rxybVDSpRTsEtZZmheO516pDw=,tag:y4+SLJg10kCQEJMsJMftuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
