---
apiVersion: v1
kind: Pod
metadata:
  name: data-editor
  namespace: home-automation
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: zigbee2mqtt-basement-data
  containers:
    - name: editor
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
