---
apiVersion: dbman.hef.sh/v1alpha2
kind: DatabaseServer
metadata:
  name: nas-postgres17
spec:
  connString: "host=nas-postgres17-rw.database-system"
  credentials:
    basicAuthSecretRef: postgres-superuser
