# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-minio
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Cr+hsPke+L4mbw==,iv:p3jB41TVkc4zDNqzQWuAM4qmYZBkALcHzIh0zaQjrxc=,tag:dJx2w/6T2ORMrmIm6fzyrA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:08c2yYfD1OMc1w==,iv:fh4DuLqxAvfDGTw3Zy+JcIw0mJRUiK8e8kk8pIG+eRU=,tag:tUyq/JXpy8e4NsHt+zMUtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM3IrV3NScGN5amNxd2ha
            aWZDaXh0Si9XSi9COUNWUzdkeVZKRXZ3c3drCi9SY05Qa0NWVVo4QTVNU1dVWWxk
            N3lVQnl3UmYyejRWRCsrOTNpdUtxeTgKLS0tIFhWTkpHL0daV3lNTnFuT0d1ZkVX
            bFhFS2FrbW5CekwwVGhnRHpYR1dBZTAKbzgMPb7qOA/Urst1j/pcamZD6mB+WRF0
            tHpsqQ52+B7Epy4f4vZWqgsJOIEtFyis+9P4Bjqe1XfFi3G2hhHODA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T23:29:32Z"
    mac: ENC[AES256_GCM,data:WaPmV3Vlhxet7mn+ZKlNUy+0jjNphVlPxvQWCCqcpFPYeU2h7v66mQIm8cktsXUiysdUdMnWqeyp3lwEhgyLfm72i7N8dUFX5RoM2z6EKhwEwNH67X5KnB2TOMnccNqhhZySgACZbt07Ic0bw8VHzKgm93X5qx3SGQ8j07FdPz0=,iv:8PCqBzumhl4W9PkeqoozgwCWPIzpMT1q7105zsP0vbA=,tag:UxSk+Vihu1B+yGxf0gpOHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
