# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    labels:
        cnpg.io/cluster: nas-postgres17
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:OZJ54UhyxFc=,iv:AHoqU80QX6Jl2x308+KCN9geRH7iABx/44u6JO+Kmww=,tag:Rjr1/NeOaVEPg7Fe2BhLdQ==,type:str]
    password: ENC[AES256_GCM,data:a6hD3D4OT6Qj++xGNOKnh5ORNw4DEF7n+TRK7Lml7xA=,iv:6trQJL7nbNrrl7KJ4kcKCJ7RzWfE52b4WaqsmCJSGFE=,tag:x91aWG3iZt9pDPS7JPq5dQ==,type:str]
    dbname: ENC[AES256_GCM,data:xK0KGjkFUT4=,iv:J2QaVnc2twmqHawZ/riKx5g3jQRf3b//ip88FdBDrV4=,tag:TwpMIyPEv89VJhvyTgzGJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ2QvOUZvNUpvZGs4eEhQ
            c0dOYUtmUC9WL3VHOVUrYWUzQzhobUF4cEJRCkdjbjd1aGlwY2UvWDRyWjhjOEpr
            VGdwa1drelN3bUhCdTVvZWQ4UkpRNEUKLS0tIERFUHI5OWV5UDIvR2dVV1JWZGxm
            L3IvQ0NLWWQ5UmVNTTV4OHMxR0RaNVEKK3cldYMM7mPGfj+tImVOXmJdrnX8rGvT
            qNgsAFtlMaX9gr6TxRdJGTt/RQoYnesdGzemAvsFClYtJ97EYZq8OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T21:46:39Z"
    mac: ENC[AES256_GCM,data:7bxP2mJuPvmgu3Xxkz9jvFt2R4iX2Qh1K6DuKbnrKrVDNG7KGzUmFkGHgei/aOxg77PVyrTVa/VV3B63AynqHBhBGgbIn9PdHYdQPrP968T1ltc9b3Hm+Zje4aXBnb/h7TH3YIakKy2ckd6NB+j8ESKlCi7Tgen8Pdv7QZE23Fs=,iv:t/S5SP2S213JAfKh9zied8FWmFpu0caUvRyGE5b+q3s=,tag:Y/2O6rxVLeJEFIHzc3JF6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
