# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    labels:
        cnpg.io/reload: ""
stringData:
    username: ENC[AES256_GCM,data:OZJ54UhyxFc=,iv:AHoqU80QX6Jl2x308+KCN9geRH7iABx/44u6JO+Kmww=,tag:Rjr1/NeOaVEPg7Fe2BhLdQ==,type:str]
    password: ENC[AES256_GCM,data:a6hD3D4OT6Qj++xGNOKnh5ORNw4DEF7n+TRK7Lml7xA=,iv:6trQJL7nbNrrl7KJ4kcKCJ7RzWfE52b4WaqsmCJSGFE=,tag:x91aWG3iZt9pDPS7JPq5dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ2QvOUZvNUpvZGs4eEhQ
            c0dOYUtmUC9WL3VHOVUrYWUzQzhobUF4cEJRCkdjbjd1aGlwY2UvWDRyWjhjOEpr
            VGdwa1drelN3bUhCdTVvZWQ4UkpRNEUKLS0tIERFUHI5OWV5UDIvR2dVV1JWZGxm
            L3IvQ0NLWWQ5UmVNTTV4OHMxR0RaNVEKK3cldYMM7mPGfj+tImVOXmJdrnX8rGvT
            qNgsAFtlMaX9gr6TxRdJGTt/RQoYnesdGzemAvsFClYtJ97EYZq8OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T22:25:26Z"
    mac: ENC[AES256_GCM,data:zaqRANhyfgl2vakneHhXQldjuEuvpBRqdRWJRYAzTLLmPl4pxtL2E4/QK4Rc8I3+9YqqzpBwKelFTpRCBoMLSwbqVHQMbXCrR8dTwZg5YuZIakbU5qCt4MJJP3KE+iOjpLvZ3XOYYccOnNY0Z+t11yH8fT0HYbquXshaa7D6ebo=,iv:JVs7ZkB810bVFI1JnsJag6SLQ/zKC7dimZ72qUGQMao=,tag:mQtdwIWc9lDjggQHQMXW+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
