---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nas-postgres16
  namespace: database
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: nas-postgres16
