---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-public-velocity-proxy
spec:
  interval: 15m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      velocity:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            ingress.home.arpa/playit: allow
          securityContext:
            fsGroup: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            nameOverride: *app
            # envFrom:
            #   - secretRef:
            #       name: bungeecord-rcon
            env:
              UID: "1000"
              GID: "1000"
              TYPE: "VELOCITY"
              VELOCITY_VERSION: "latest"
              VELOCITY_BUILD_ID: "latest"
              PLUGINS: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity,https://cdn.modrinth.com/data/9eGKb6K1/versions/yGTasgG4/voicechat-velocity-2.5.24.jar,https://cdn.modrinth.com/data/jwCN0QR7/versions/n8UMZLCH/Vitelist-2.0.jar
              MEMORY: 256M
              # JVM_OPTS: "-Xms128M -Xmx256M"
              ENABLE_RCON: "false"
              SPIGOT_PLUGIN: "78915"
              TZ: ${SETTING_TZ}

            image:
              repository: itzg/bungeecord
              tag: latest@sha256:82b6a7b7d9aefbee26ce2c95e399d5e8dde073f5e6e87e6462f4016fca9f52f3
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            ports:
              - name: velocity
                containerPort: &port 25565
                protocol: TCP
              - name: bedrock
                containerPort: &bedrockPort 19132
                protocol: UDP
              - name: simplevoicechat
                containerPort: &simplevoicechatPort 24454
                protocol: UDP
              # - name: rcon
              #   containerPort: &rconPort 25575
              #   protocol: TCP

            probes:
              readiness: &probes
                enabled: true
                type: TCP
                port: *port
              liveness: *probes
              startup:
                <<: *probes
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                cpu: 50m
                memory: 250Mi

    service:
      velocity:
        controller: velocity
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SETTING_CILIUM_MINECRAFT_PROXY_ADDR3}
        ports:
          velocity-proxy:
            port: *port
            protocol: TCP
            targetPort: velocity
          bedrock-proxy:
            port: *bedrockPort
            protocol: UDP
            targetPort: bedrock
          simplevoicechat-proxy:
            port: *simplevoicechatPort
            protocol: UDP
            targetPort: simplevoicechat
      # rcon:
      #   controller: velocity
      #   ports:
      #     rcon:
      #       port: *rconPort
      #       protocol: TCP
      #       targetPort: rcon

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      data:
        type: persistentVolumeClaim
        existingClaim: minecraft-public-velocity-proxy-data
        globalMounts:
          - path: /server
      config:
        type: configMap
        name: minecraft-public-velocity-proxy-config
        globalMounts:
          - path: /config/velocity.toml
            subPath: velocity.toml
            readOnly: true
          - path: /config/forwarding.secret
            subPath: forwarding.secret
            readOnly: true
