---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-public-velocity-proxy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
