---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: data-vault-0
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
