---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-vault-0
spec:
  sourcePVC: data-vault-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: vault-volsync
    volumeSnapshotClassName: nfs-csi-snapshot
    cacheCapacity: 1Gi
    cacheStorageClassName: nfs-csi
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: nfs-csi
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
