---
# yaml-language-server: $schema=https://kubernetes-schemas.minuette.horse/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kube-nas-vault
spec:
  provider:
    vault:
      server: https://vault.tyriis.dev
      path: infra/kube-nas
      version: v2
      auth:
        kubernetes:
          role: kube-nas
          mountPath: kubernetes
          serviceAccountRef:
            name: vault-auth
            namespace: secops
