---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth-system
resources:
  - secrets.sops.yaml
  - helm-release.yaml
