# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-env-secrets
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:GGIHy6P/Ol+/yOqqDpicQ376dYqPxdfkYGubLxroH2EJV0IFsxHocP257zUAhJV4jzjv0L5Cih4ID63Xtfe3u137kAuxQGtC,iv:ldPY6AeAy2lSrKJUHlPST/2w6Z7L0zyEJQUhGUI6RXM=,tag:bBq3pve/0vlj6/udqafViQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:/E48UfNfDmSfu5kaRE5iDxdCA5OHiZn1w4DlPgNoUH4KI3M=,iv:AnmHqbapcqWlrQ12qhx25Ea3mZ9wldGsCCmoipMjKS0=,tag:YYvi8O/kbCTk8WXYI1NngQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:YfBa0Q/2thg5c77SEOzDHRWejd9u8q6QsWiPpFS9h4P6o3ciDDCppSxhhc4=,iv:ZwQ0cirhF+4vDwXEmhoN3W+anXbDHijn6x2AlyGmWvE=,tag:W3NKF1a9iaI7YEgOPgieGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clg0rd6ca86h3lnfnjyqsc9stgr0cnyp3l5uswtusxppjq9h2vcsaqckec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzRWUkxIMnA1Nm5MSFVP
            anliQ3F3R1VyWVVNak5mUm5ST3dsSnFRY1hrCkpONU50NGsyUWlhNkYyL3lqN1h5
            VXdSZ0g2NnFsS0loMERMWmZIbGdob28KLS0tIE83RHBlY2FYd0F0YklBRThQd2tl
            TVM4dVYwY3ExYkIxSmJoK3V5VEJNQ2MKs9lDocwW5M7BmdvfvOABbjuffo16CJok
            djKyN7RS86g3cstMR5X4uKoC+UFS6F4+xkNVtJoc6mZS71ZN4RU2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T21:55:04Z"
    mac: ENC[AES256_GCM,data:nBKTJJPWXSZbw/UEStfpdj+pdCQ2PwEROArQQKzMsF48gCL3rF2b4n0fGs9pOpv70HorLmg5n6UE+Y2loEUdy9D2Rwu3MIged3Rogm3FXoGe8SI1JqT48Bfjtr1TTSzDF3d3WgnepR3pz6dyaA+60KiYdXsXql9080OR47ZRFUo=,iv:WncdGmoD8WNImrMo13LwHCxAe0LilfASRns0I8B5PHk=,tag:N9S9Q1HDfkdfviTkbenk0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
