---
# only applied once during bootstrap
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:5050"
    hostFromContainerRuntime: "home-ops-kind-registry:5000"
    hostFromClusterNetwork: "home-ops-kind-registry:5000"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
