---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  dependsOn:
    - name: dragonfly-cluster
  interval: 10m
  path: ./kubernetes/kube-nas/apps/auth-system/oauth2-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  targetNamespace: auth-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: oauth2-proxy
  wait: true
