---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname volsync
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  targetNamespace: backup-system
  dependsOn:
    - name: snapshot-controller
  interval: 10m
  path: ./kubernetes/kube-nas/apps/backup-system/volsync/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  timeout: 3m
