# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: govee2mqtt-env
    labels:
        app.kubernetes.io/instance: govee2mqtt
        app.kubernetes.io/name: govee2mqtt
stringData:
    #ENC[AES256_GCM,data:mqqdEj/vi3C3p0EEg7zHTs5c+z5Fx9I/+AFKK4r6vGTBeDkv9lvN3Z0BO2LLY/G6dlZWXtLTND97wmDy7pun,iv:j4Zy2fjBRFxie+uYttbMYZQYYSi71vQ2mReHn2qIvxk=,tag:sLTDMBucgJ1TZ5GgnRcLZg==,type:comment]
    GOVEE_EMAIL: ENC[AES256_GCM,data:E9/DFe7NTVGq3B7pb1LSxTW/OYM6aqo=,iv:gT1ZgUXGDPD57G3gj2jwuWBSG2Pyoxaqv/KXt6NSF7A=,tag:VtKZdLf1H14uneX1LpIcww==,type:str]
    GOVEE_PASSWORD: ENC[AES256_GCM,data:a6PvuIEc3H2I,iv:8YkUefDC4/s7UiaTgjd5mwyB2Uz9CuA9rMQ5RIdoFH0=,tag:1X/LafcsmjIIkn7f3AlChg==,type:str]
    GOVEE_API_KEY: ENC[AES256_GCM,data:yCtRhcJ6Ccl/cHcx8X7Z7TEOCUn1VUzl9jpjDvnQtgK/Z2tH,iv:/B8rIIcoZLIwNuLpau9zvjtxB0n4c24XxW2nHzNoeqE=,tag:KegWHx/HcGsOIE3yTd7ArQ==,type:str]
    #ENC[AES256_GCM,data:2TBfvejFChrmOess7hA9vg==,iv:rmHPAMBKPAdnnpeKPSSdg5kyHjvHRPs2pWxRPb4OSYs=,tag:PDN1HduD6QRowYJqKoYCPg==,type:comment]
    #ENC[AES256_GCM,data:G9F5cw+ItMFB1wRUnf26A2MGQGo=,iv:S/4GlsUkFPkihmkbh1MWLU95D3vZfCsjF5b6jhR4m/M=,tag:L0CCsBaxLjqaZTwTj0ciIw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T20:43:31Z"
    mac: ENC[AES256_GCM,data:X2UPnkz4sRXHKUZo6ba9TicJ81amF3B+ASfPD54lEPMVozezoroMRzUPw4mp3qth/UqEw7FExbv4lHQN7qbRCagJGEZR2KnK4D6qxHMW9ie4QtdPGWjGdsAv1pRFgSP4AUmkGktjsFAMfhFLV/GUMDebxls5e+c4rhuL0Sum2+w=,iv:BcY/qndHDw8/OC+AuPhwjxRs2rMuS0A52oPzU3Gv0fA=,tag:8yyKkvuZqrbzbioccw/raQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
