---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-data
spec:
  sourcePVC: home-assistant-data
  trigger:
    schedule: "17 2 * * *" # 2:17 AM
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 1
    repository: home-assistant-volsync
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 10Mi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 7
      weekly: 4
      monthly: 3
