---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - helm-release.yaml
  - prometheus-rule.yaml
  - service-monitor.yaml
commonLabels:
  app.kubernetes.io/instance: speedtest-exporter
  app.kubernetes.io/name: speedtest-exporter
