---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
commonLabels:
  app.kubernetes.io/name: minecraft-creative-world
  app.kubernetes.io/instance: minecraft-creative-world
configMapGenerator:
  - name: minecraft-creative-world-config
    files:
      - spigot.yml=config/spigot.yaml
      - paper-global.yml=config/paper-global.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
