---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - secret.sops.yaml
  - replication-destination.yaml
  - persistent-volume-claim.yaml
  - replication-source.yaml
  - helm-release.yaml
configMapGenerator:
  - name: minecraft-creative-world-config
    files:
      - spigot.yml=config/spigot.yaml
      - paper-global.yml=config/paper-global.yaml
      - plugins.txt=config/plugins.txt
  - name: minecraft-creative-world-plugins
    files:
      - bluemap_sql.conf=plugins/BlueMap/storage/sql.conf
      - bluemap_core.conf=plugins/BlueMap/core.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
