---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-creative-world-data
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: minecraft-creative-world-data
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
