# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-creative-world-data-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:I78cc8FKGTK/ei/wBDvxEYCjeLBcNEOhzvDnVUzdhuAsUeAMFnqRiTFR7s3Q+++j8P0S5CiAhY2PfPdY1DBPPbuUrwmt6Drtb1kT2aM=,iv:Orkyb+FaUeQEbdq/QAcGTi8GzYdRMbeu0Em7ysD1L14=,tag:hAMPb9qtMNItJjV8WT7UfQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:3UHkZkvo6C5ISl+K9Jt99MNkcYr51lnAnpI+x0EPRz5j3KDYbtsT/09XGHFRUei6b28Ed4OyeC64eosjifmT2g==,iv:r7mU2+Iop/kJrn6NmOziKWkzNndzEzWp/kcHUUyiSj4=,tag:SNZ5IoeNTkSwFdEhwovF1w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T10:21:40Z"
    mac: ENC[AES256_GCM,data:FOwa237uRnIs6BKBEOmn0b4Y0qUj47MAWiXAOj6Fae+XY7JxfGvWkLIg/uy82ZOm2O2dEJMxZP6EGWuS3us68nNsi4nFRHAE8FR5IoNjo3BEt+HNkOIzpeF7HW2QJPkMrlORzMRDxv2khIykN/6AUwaEdyR9bEEE1Vrt0jlbc9g=,iv:wkjkHTLllpSKHRWtI9W8so7ke72Q48X2TF9/bs0BE+4=,tag:5IHhSkTdj45DWx5tnMkMng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
