# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2L1IjnIrXz7Zsdhzoo9Y6M6BqgvAa7X3xrDKaRNOoeERAxsG0B6QGTzixpGufPVKlqXACihh0rcXKhCbRbsGp+X8reXjluvX1w==,iv:A/Sslih5siwjrqNyELR+vtO/xkcsfd/HR6WeVSqXd10=,tag:KIAQAlH56ZQvKzvSpq2k3g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EtWX8MQD7M+cON3zQFmMbbjsndNYQ/nXfvnwcu4FlthGs45iHpP8/9TJhKo1CnxjIqGxa2HGWTmthVztvFzwFKj8KYrmLUgQRKIogGrq+wMsAaYLcM6zhw==,iv:AZ3NU1+wxmnHxVOJeP2OUVcnVPUdXC4VoWp7dj12suY=,tag:pB7o/tk7OiP6lLU9iHjsUQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T19:43:31Z"
    mac: ENC[AES256_GCM,data:4FMM5SrfFZ8tR1XcV01J8jQJ7Yi9346/Gvg4Ja/cb8vzvp5hU988sidsLqNgIG+9LMIwwpF5dgV6uEp0I8dpNxFOSa0nQfCik5AkEHrAL5S+K+ocy9SBsLjuJQ30e78jyPzUw0wJShKJUC5A1Z1cmrBE2kIosLBZaRhOgDXvKnY=,iv:StuPx68GkmqtxHs2QKnk/M0viWGk87etIrpg1a89YbQ=,tag:zBeabdsh7P/yIJids5B3lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
