---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-zigbee2mqtt-basement-storage
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/basement-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-rook-ceph-cluster
    - name: apps-volsync
    - name: apps-kube-prometheus-stack
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: apps-zigbee2mqtt-basement
#   namespace: flux-system
#   annotations:
#     backstage.io/discovery: enabled
#     backstage.io/name: zigbee2mqtt-basement
#   labels:
#     substitution.flux.home.arpa/enabled: "true"
# spec:
#   interval: 10m
#   path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/basement
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
#   wait: true
#   dependsOn:
#     - name: apps-zigbee2mqtt-basement-storage

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-zigbee2mqtt-downstairs-storage
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/downstairs-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-rook-ceph-cluster
    - name: apps-volsync
    - name: apps-kube-prometheus-stack

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-zigbee2mqtt-downstairs
  namespace: flux-system
  annotations:
    backstage.io/discovery: enabled
    backstage.io/name: zigbee2mqtt-downstairs
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/downstairs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-zigbee2mqtt-downstairs-storage

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-zigbee2mqtt-upstairs-storage
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/upstairs-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-rook-ceph-cluster
    - name: apps-volsync
    - name: apps-kube-prometheus-stack
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-zigbee2mqtt-upstairs
  namespace: flux-system
  annotations:
    backstage.io/discovery: enabled
    backstage.io/name: zigbee2mqtt-upstairs
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/upstairs
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: apps-zigbee2mqtt-upstairs-storage

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
  namespace: flux-system
  # annotations:
  #   backstage.io/discovery: enabled
  #   backstage.io/name: zigbee2mqtt-downstairs
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: ./kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  timeout: 5m
  dependsOn:
    - name: apps-rook-ceph-cluster
    - name: apps-volsync
    - name: apps-kube-prometheus-stack
    - name: apps-external-secrets-stores
