---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis-tyriis
spec:
  interval: 15m
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values
  values:
    config:
      type: configMap
      name: atlantis-default-config
      advancedMounts:
        main:
          app:
            - path: /etc/atlantis/repos.yaml
              subPath: repos.yaml
              readOnly: true
    persistence:
      scripts:
        type: configMap
        name: atlantis-default-scripts
        advancedMounts:
          main:
            app:
              - path: /home/atlantis/scripts
                readOnly: true
      allowlist:
        type: configMap
        name: atlantis-tyriis-allowlist
        advancedMounts:
          main:
            app:
              - path: /etc/atlantis/allowlist.txt
                subPath: allowlist.txt
                readOnly: true
