---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: atlantis-tyriis-config
    files:
      - repoConfig=config/repos.yaml
  - name: atlantis-tyriis-allow-list
    files:
      - allowlist.txt=config/allowlist.txt
  - name: atlantis-tyriis-scripts
    files:
      - allow_list.sh=config/allow_list.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
