---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name playit
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        playit.toml: |
          api_url = "https://api.playit.cloud/agent"
          ping_target_addresses = []
          control_address = "control.playit.gg"
          refresh_from_api = true
          api_refresh_rate = 5000
          ping_interval = 5000
          secret_key = "{{ .PLAYIT_SECRET_KEY }}"
          mappings = []
  dataFrom:
    - extract:
        key: infra/techtales/network/playit
