---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cert-manager
  namespace: flux-system
  annotations:
    backstage.io/discovery: enabled
    backstage.io/name: cert-manager
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/talos-flux/apps/cert-manager/cert-manager/issuers
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
