---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: esphome-config
    files:
      - light-alexroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/light-alexroom.yaml
      - light-stairs.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/light-stairs.yaml
      - sensor-bathroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/sensor-bathroom.yaml
      - sensor-domiroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/sensor-domiroom.yaml
      - sensor-heating.yaml=sensor-heating.yaml
      - switch-alexroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-alexroom.yaml
      - switch-basement.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-basement.yaml
      - switch-domiroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-domiroom.yaml
      # - switch-heating.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-heating.yaml
      - switch-livingroom.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-livingroom.yaml
      - switch-office.yaml=https://raw.githubusercontent.com/tyriis/esphome-config/main/switch-office.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
