---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name ring-mqtt-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: "{{ .config.json }}"
        ring-state.json: "{{ .ring-state.json }}"
  dataFrom:
    - extract:
        key: infra/techtales/home-automation/ring-mqtt
