---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ring-mqtt-data
  resources:
    requests:
      storage: 10Mi
  storageClassName: ceph-block
