# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ring-mqtt-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cKZ32zpgkuv9c9N2vIpykoQ2O0foCkhDwXKG0Sstuq4xaI0aS2J+ilOWWk0wCYaBK+MNG7ov0ESoilqisdidBKTYpMDRj7Y=,iv:AMNP9Gx/Ik/j/MKtqdTiGYttZPITlcxUqS9aXVSpurE=,tag:GsH0fbCWFDv4e3sRzGmr9g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:aZN+GSkhZ1lkUNjhN5F6Ve2hRwU3Jguna7tV6wP25xJmx7OEA+6lH7WyPqD2PoUUUi1msrx85NToxFxOec2jHg==,iv:SwySPIfWkgVngdMunyjk1KWEzQ/aa3/L7zvy5Z7+xJo=,tag:EbHYG9o0g6Vqp7kubkny+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JEXZW41lEw==,iv:pduvJsbyBRNMiP6rJ5T7mz79rdW5VLpR/Y3lOXHKU8A=,tag:HZKS59FvxO4FwZrb3LhKmg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aguU70F7QhX2FSEJFmknY8+31PbPIXdF0iGArAkBIihiGhAfOMkD6upDfpZmuZYQcJJgRPpH2jk=,iv:I/9UIpgz0uXHzhhlbV4481gS9KRtm1ZhzvoxJScGsxg=,tag:ax0t2h1ltyPkk+0TgnMCIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16zqeqx5y6ay3flwz0d06rn83yjv9ckys3j8tpkysf9v6295fhc6sf4r0uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdZeVptaDlPZW9idmtP
            UkRGdmxyb0REM2s4dnZVSERQNFFSRHlqVkcwClJlZHVhQUVnUm16QVloazMyUUFx
            Q24vakF5RUEvMTExZ0lPa1RXblFEV3cKLS0tIFNMcGx3NzRQT0U4MTZER0FQUzh3
            SThDODl4ZFFMMUlxM3BneWlrNDdjdUUKm16agevW+HLV4al0q2m5W/SyS84E5SXh
            QfWlkG1byRaLRQ+tMeTuCN0tk2A2asmSPygQ1IKo4AO9kMirDEjQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T17:41:56Z"
    mac: ENC[AES256_GCM,data:4zhtkkc0AASF4O2bWCnxkNj6zfw0nfq7wc2RA9RvH9UDf1LasqchFf3dPeVtKRQpx3RaFgIwhxWgA8NzdT95bor0ZmIJJaTYl6MLVygp0a19jhLqxk8ZAdURp/JuOOVfqRkIt3KWlSuDffRUaY4SXttB7U+IVil0IvYnvsVf+0A=,iv:r3UQ81IDllGoCS4AxVkM7kTOZEL83Sd4rS56euaP3iw=,tag:SaTWt6KwXfkik+ms81goKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
