---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./namespace.yaml namespace is part of gotk manifests and will toggle reconcile
  - ./gotk/flux-sync.yaml
  - ./capacitor/flux-sync.yaml
  # - ./tofu-controller/flux-sync.yaml # disable as it does not work properly currently
